<ul class="nav navbar-nav">
    <?php foreach ($this->container as $page) { ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php $role = ($this->UserIdentity()) ? $this->UserIdentity()->getRole()->getName() : 'Visit' ; ?>
        <?php $acl = $this->Acl(); ?>
        <?php if (!$acl->isAllowed($role,$page->getResource(),$page->getPrivilege())) { continue; } else { ?>
            <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) { continue; } ?>
            <?php $hasChildren = $page->hasPages(); ?>
            <?php if (!$hasChildren) { ?>
                <li>
                    <a href="<?php echo $page->getHref() ?>">
                        <?php echo $this->translate($page->getLabel()) ?>
                    </a>
                </li>
            <?php } else { ?>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate($page->getLabel()) ?> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <?php foreach ($page->getPages() as $child) { ?>
                        <?php // when using partials we need to manually check for ACL conditions ?>
                        <?php if(!$child->isVisible() || !$this->navigation()->accept($child)) { continue; } ?>
                        <li>
                            <a href="<?php echo $child->getHref() ?>">
                                <?php echo $this->translate($child->getLabel()) ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </li>
            <?php } ?>
        <?php } ?>
    <?php } ?>
</ul>
