x<!-- TODO navigation -->
<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('US Zend2')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/assets/css/style.min.css')  ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependScript("var basePath = '".$this->basePath()."'" )
            ->prependFile($this->basePath() . '/assets/js/script.min.js')  ?>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">Undefined Source</a>
                </div>
                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <?php echo $this->navigation('navigation')->menu()->setPartial('partials/navigation-top.phtml');
                    ?>
                    <ul class="nav navbar-nav navbar-right">
                        <?php if ($this->UserIdentity()) : ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello <?php echo ($this->UserIdentity()->getPerfil()->getName()) ? $this->UserIdentity()->getPerfil()->getName() : $this->UserIdentity()->getUsername() ; ?>! <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Meus Dados</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url('user-auth/default', array('action' => 'logout')) ?>">Logout</a></li>
                                </ul>
                            </li>
                        <?php else: ?>
                            <li>
                                <a href="<?php echo $this->url('user-auth') ?>">Login</a>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div>

            </div><!-- /.container -->
        </nav>
        <!-- MAIN CONTENT -->
        <div class="container" style="padding-top: 80px;">
            <?php echo $this->content; ?>
            <div class="text-center col-xs-12"><?php echo $this->Version(); ?></div>
        </div>

        <!-- END MAIN CONTENT -->

        <?php echo $this->inlineScript() ?>
    </body>
</html>
