<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Zf2SkeletonApp')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/assets/css/main.css')
            ->prependStylesheet($this->basePath() . '/library/fontawesome/css/font-awesome.min.css')
            ->prependStylesheet($this->basePath() . '/library/bootstrap/css/bootstrap.min.css')  ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependScript("var basePath = '".$this->basePath()."'" )
            ->prependFile($this->basePath() . '/assets/js/app.js')
            ->prependFile($this->basePath() . '/library/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/library/jquery/jquery-1.11.0.min.js')
            ->prependFile($this->basePath() . '/library/base/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/library/base/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))  ?>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">Zf2SkeletonApp</a>
                </div>

            </div><!-- /.container -->
        </nav>

        <!-- MAIN CONTENT -->
        <div class="container" style="padding-top: 80px;">
            <?php echo $this->content; ?>
            <div class="text-center col-xs-12"><?php echo $this->Version(); ?></div>
        </div>

        <!-- END MAIN CONTENT -->

        <?php echo $this->inlineScript() ?>
    </body>
</html>
