<div class="jumbotron">
    <h1><?php echo sprintf('Welcome to %sZend Framework 3%s', '<span class="zf-green">', '</span>') ?></h1>
    <p>Skeleton Zend 3 + Admin + Authentication + Acl + Register User.') ?></p>
    <p>Its Login => Login: developer Password:123456') ?></p>
    <p>Access your customer => Login: admin Password:123456') ?></p>
    <p>Access the employee of his client => Login: functionary Password:123456') ?></p>
    <p>Access your customer's customer => Login: client Password:123456 obs: no active") ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/jhonmike/StartAppZend3" target="_blank">Fork Admin on GitHub &raquo;</a>
    <a class="btn btn-success btn-lg" href="<?php echo $this->url('user-auth'); ?>">Login &raquo;</a>
    <a class="btn btn-success btn-lg" href="<?php echo $this->url('user-auth/default',array('action'=>'register')); ?>">Register &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">ZfBase</h3>
            </div>
            <div class="panel-body">
                <p>CrudController, Mail, AbstractService, AbstractUpload</p>
                <p><a class="btn btn-success pull-right" href="https://github.com/jhonmike/zf-base" target="_blank">ZfBase &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">ZfAcl</h3>
            </div>
            <div class="panel-body">
                <p>Role, Resource, Privilege</p>
                <p><a class="btn btn-success pull-right" href="https://github.com/jhonmike/zf-acl" target="_blank">ZfAcl &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">ZfUser</h3>
            </div>
            <div class="panel-body">
                <p>User, Authentication</p>
                <p><a class="btn btn-success pull-right" href="https://github.com/jhonmike/zf-user" target="_blank">ZfUser &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
