<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo $this->translate('Skeleton Zend 2 + Admin + Authentication + Acl + Register User.') ?></p>
    <p><?php echo $this->translate('Its Login => Login: developer Password:123456') ?></p>
    <p><?php echo $this->translate('Access your customer => Login: admin Password:123456') ?></p>
    <p><?php echo $this->translate('Access the employee of his client => Login: functionary Password:123456') ?></p>
    <p><?php echo $this->translate("Access your customer's customer => Login: client Password:123456 obs: no active") ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/jhonmike/Zf2SkeletonApp" target="_blank"><?php echo $this->translate('Fork Admin on GitHub') ?> &raquo;</a>
    <a class="btn btn-success btn-lg" href="<?php echo $this->url('user-auth'); ?>"><?php echo $this->translate('Login') ?> &raquo;</a>
    <a class="btn btn-success btn-lg" href="<?php echo $this->url('user-auth/default',array('action'=>'register')); ?>"><?php echo $this->translate('Register') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo 'Zf2Base' ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('CrudController, Mail, AbstractService, AbstractUpload') ?></p>
                <p><a class="btn btn-success pull-right" href="https://github.com/jhonmike/Zf2Base" target="_blank"><?php echo 'Zf2Base' ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo 'Zf2Acl' ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Role, Resource, Privilege') ?></p>
                <p><a class="btn btn-success pull-right" href="https://github.com/jhonmike/Zf2Acl" target="_blank"><?php echo 'Zf2Acl' ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo 'Zf2User' ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('User, Authentication') ?></p>
                <p><a class="btn btn-success pull-right" href="https://github.com/jhonmike/Zf2User" target="_blank"><?php echo 'Zf2User' ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
